version: "2"
services:
  site:
    command: jekyll serve --watch --incremental
    image: jekyll/jekyll:pages
    environment:
      - VIRTUAL_HOST=jeremyredd.com,blog.jeremyredd.com
      - LETSENCRYPT_HOST=jeremyredd.com,blog.jeremyredd.com
      - LETSENCRYPT_EMAIL=contact@jeremyredd.com
    volumes:
      - $PWD:/srv/jekyll
      - $PWD/vendor/bundle:/usr/local/bundle
    ports:
      - 4000:4000
      - 35729:35729
      - 3000:3000
